### ISSUE TITLE
uploded image not displayed blocks

### ISSUE THREAD

**Issue by dns144** [BlockySite/community#4] opened 2021-11-26 13:36 UTC
### Service

β.creator.blockysite.com

### What happened?

![image](https://user-images.githubusercontent.com/95041758/143589021-2f6fde39-956d-4130-b794-e1100a7f2c48.png)

### What browser do you use?

Chrome

**Comment by suryadevelope** [comment] 2021-11-26 16:19
@dns144 hello this is suryaprakash front end developer of blockysite

nice to meet you ,wish you a warm welcome

**Comment by suryadevelope** [comment] 2021-11-26 19:00
@shiva-sandupatla update set_style_display_backgroundimage block code as below

`Blockly.Blocks.set_style_display_backgroundimage={
  init:function(){
    this.appendDummyInput().appendField("set")
    .appendField(new Blockly.FieldDropdown(BlockySite.Extension.bsc.bSstyles30062021043321idsss),"component")
    .appendField(".style of")
    .appendField(new Blockly.FieldDropdown([["backgroundImage","backgroundImage"]]),"style")
    .appendField(".to")
    .appendField(new Blockly.FieldDropdown(
      this.generateOptions),"value"),
    this.setPreviousStatement(!0,null),
    this.setNextStatement(!0,null),
    this.setColour(Blockly.Block_color.SETTER_BLOCK_COLOUR),
    this.setTooltip(BlockySite.addon.blocks.setter_block.type.set_style_display_backgroundimage.toolTip),this.setHelpUrl(BlockySite.addon.blocks.setter_block.type.set_style_display_backgroundimage.helpUrl)},generateOptions: function() {
      return Object.assign([],window.bbmedia["img"]).map(e => [e.text,e.text])
    }}`

**Comment by dns144** [comment] 2021-11-27 16:22
ok issue is fixed @suryadevelope

**Comment by shiva-sandupatla** [comment] 2021-11-28 11:28
as @dns144, told that issue is fixed. So I verified that the issue is resolved and I am closing this issue. Thank you @dns144 for your report and thank you @suryadevelope  for fixing it

**Closed by shiva-sandupatla** 2021-11-28 11:28 UTC
Labels: Done
